load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name       = "fourditor",
    srcs       = glob(["src/main/java/**/*.java"]),
    main_class = "dev.fempolyhedron.fourditor.Main",
    visibility = ["//visibility:public"],
)
